### ISSUE TITLE
[FE] 도서 등록 시 등록버튼 작동하지 않는 현상

### ISSUE THREAD

**Issue by phantom08266** [dukki-labs/litarary#114]
도서 등록을 하려고 하는데 등록버튼을 눌러도 요청메시지를 보내지 않는것 같아요. 확인한번 부탁드려요!

**Comment by ted-han** [comment]
@phantom08266 준희님 페이지네이션은 아직 못했는데 우선 등록하기 가능하도록 수정해서 배포했어요.
